## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN"])
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_df["APPLICATION_TYPE"].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = [["T9", "T13", "T12", "T2", "T25", "T14", "T29", "T15", "T17"]]

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
application_df["CLASSIFICATION"].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = application_df["CLASSIFICATION"].value_counts()
counts_greater_than_one = classification_counts[classification_counts >1]
print(counts_greater_than_one)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = [["C1700", "C4000", "C5000", "C1270", "C2700","C2800", "C7100", "C1300", "C1280", "C1230", "C1400", "C7200", "C2300", "C1240",
                              "C8000", "C7120", "C1500", "C1800", "C6000", "C1250", "C8200", "C1238", "C1278", "C1235", "C1237", "C7210", "C2400", "C1720",
                              "C4100", "C1257", "C1600", "C1260", "C2710", "C0", "C3200", "C1234", "C1246", "C1267", "C1256", "C1370", "C1236", "C2190",
                              "C4200", "C5200", "C6100", "C2600", "C1248", "C1580", "C1820", "C1900", "C2570", "C1283", "C3700", "C2500", "C1570", "C2380",
                              "C1732", "C1728", "C2170", "C4120", "C8210", "C4500", "C1245", "C2561", "C2150"]]

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: count, dtype: int64

In [9]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"]
X = application_df.drop(columns= "IS_SUCCESSFUL")

# Convert categorical data to numeric with `pd.get_dummies`
X = pd.get_dummies(X)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [10]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [11]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
n_features = len(X_train_scaled[0])
print(n_features)

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=40, activation="relu", input_dim=n_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=20, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

19612
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 40)                784520

 dense_1 (Dense)             (None, 20)                820

 dense_2 (Dense)             (None, 1)                 21

=================================================================
Total params: 785361 (3.00 MB)
Trainable params: 785361 (3.00 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [12]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [13]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 5s 5ms/step - loss: 0.4987 - accuracy: 0.7565
Epoch 2/100
804/804 [==============================] - 4s 5ms/step - loss: 0.1590 - accuracy: 0.9394
Epoch 3/100
804/804 [==============================] - 4s 5ms/step - loss: 0.1012 - accuracy: 0.9599
Epoch 4/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0964 - accuracy: 0.9606
Epoch 5/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0936 - accuracy: 0.9619
Epoch 6/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0925 - accuracy: 0.9618
Epoch 7/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0915 - accuracy: 0.9625
Epoch 8/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0914 - accuracy: 0.9621
Epoch 9/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0907 - accuracy: 0.9621
Epoch 10/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0898 - accuracy: 0.9626
Epoch 11/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0888 - accuracy: 0.9628
Epoch 12/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0884 - accuracy: 0.9628
Epoch 13/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0879 - accuracy: 0.9633
Epoch 14/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0873 - accuracy: 0.9634
Epoch 15/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0868 - accuracy: 0.9641
Epoch 16/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0865 - accuracy: 0.9642
Epoch 17/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0857 - accuracy: 0.9640
Epoch 18/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0858 - accuracy: 0.9647
Epoch 19/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0852 - accuracy: 0.9647
Epoch 20/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0853 - accuracy: 0.9640
Epoch 21/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0850 - accuracy: 0.9648
Epoch 22/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0846 - accuracy: 0.9651
Epoch 23/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0842 - accuracy: 0.9652
Epoch 24/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0839 - accuracy: 0.9656
Epoch 25/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0838 - accuracy: 0.9653
Epoch 26/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0830 - accuracy: 0.9663
Epoch 27/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0830 - accuracy: 0.9659
Epoch 28/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0830 - accuracy: 0.9660
Epoch 29/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0830 - accuracy: 0.9658
Epoch 30/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0822 - accuracy: 0.9659
Epoch 31/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0824 - accuracy: 0.9666
Epoch 32/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0818 - accuracy: 0.9665
Epoch 33/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0815 - accuracy: 0.9659
Epoch 34/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0813 - accuracy: 0.9665
Epoch 35/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0815 - accuracy: 0.9665
Epoch 36/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0815 - accuracy: 0.9666
Epoch 37/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0811 - accuracy: 0.9666
Epoch 38/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0809 - accuracy: 0.9666
Epoch 39/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0807 - accuracy: 0.9671
Epoch 40/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0807 - accuracy: 0.9670
Epoch 41/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0804 - accuracy: 0.9668
Epoch 42/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0803 - accuracy: 0.9670
Epoch 43/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0802 - accuracy: 0.9668
Epoch 44/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0801 - accuracy: 0.9672
Epoch 45/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0801 - accuracy: 0.9672
Epoch 46/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0798 - accuracy: 0.9673
Epoch 47/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0796 - accuracy: 0.9671
Epoch 48/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0796 - accuracy: 0.9669
Epoch 49/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0795 - accuracy: 0.9675
Epoch 50/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0795 - accuracy: 0.9675
Epoch 51/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0794 - accuracy: 0.9670
Epoch 52/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0797 - accuracy: 0.9672
Epoch 53/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0790 - accuracy: 0.9672
Epoch 54/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0791 - accuracy: 0.9675
Epoch 55/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0787 - accuracy: 0.9677
Epoch 56/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0787 - accuracy: 0.9673
Epoch 57/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0788 - accuracy: 0.9678
Epoch 58/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0786 - accuracy: 0.9674
Epoch 59/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0784 - accuracy: 0.9669
Epoch 60/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0788 - accuracy: 0.9673
Epoch 61/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0782 - accuracy: 0.9674
Epoch 62/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0782 - accuracy: 0.9674
Epoch 63/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0782 - accuracy: 0.9675
Epoch 64/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0783 - accuracy: 0.9680
Epoch 65/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0781 - accuracy: 0.9676
Epoch 66/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0783 - accuracy: 0.9678
Epoch 67/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0778 - accuracy: 0.9673
Epoch 68/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0777 - accuracy: 0.9680
Epoch 69/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0779 - accuracy: 0.9682
Epoch 70/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0778 - accuracy: 0.9673
Epoch 71/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0779 - accuracy: 0.9679
Epoch 72/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0775 - accuracy: 0.9677
Epoch 73/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0772 - accuracy: 0.9682
Epoch 74/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0776 - accuracy: 0.9680
Epoch 75/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0780 - accuracy: 0.9679
Epoch 76/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0775 - accuracy: 0.9680
Epoch 77/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0774 - accuracy: 0.9679
Epoch 78/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0770 - accuracy: 0.9683
Epoch 79/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0779 - accuracy: 0.9681
Epoch 80/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0774 - accuracy: 0.9683
Epoch 81/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0770 - accuracy: 0.9681
Epoch 82/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0774 - accuracy: 0.9682
Epoch 83/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0775 - accuracy: 0.9676
Epoch 84/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0767 - accuracy: 0.9683
Epoch 85/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0770 - accuracy: 0.9684
Epoch 86/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0767 - accuracy: 0.9687
Epoch 87/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0768 - accuracy: 0.9683
Epoch 88/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0767 - accuracy: 0.9681
Epoch 89/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0767 - accuracy: 0.9683
Epoch 90/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0767 - accuracy: 0.9683
Epoch 91/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0766 - accuracy: 0.9685
Epoch 92/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0763 - accuracy: 0.9684
Epoch 93/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0763 - accuracy: 0.9684
Epoch 94/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0763 - accuracy: 0.9686
Epoch 95/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0764 - accuracy: 0.9687
Epoch 96/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0767 - accuracy: 0.9685
Epoch 97/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0762 - accuracy: 0.9684
Epoch 98/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0764 - accuracy: 0.9683
Epoch 99/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0765 - accuracy: 0.9684
Epoch 100/100
804/804 [==============================] - 4s 5ms/step - loss: 0.0764 - accuracy: 0.9683

In [14]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.6716 - accuracy: 0.6851 - 582ms/epoch - 2ms/step
Loss: 0.6715819239616394, Accuracy: 0.6851311922073364

In [15]:
# Export our model to HDF5 file
nn.save('/content/drive/MyDrive/Colab Notebooks/Deep_Learning_Optimized_2.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(